package com.mismayilov.common.unums

enum class CurrencyType (val symbol: String, val value: String) {
        USD("$", "United States Dollar"),
        AZN("₼", "Azerbaijani Manat"),
        TRY("₺", "Turkish Lira"),
        EUR("€", "Euro"),
        SGD("SGD", "Singapore Dollar"),
        MYR("MYR", "Malaysian Ringgit"),
        AUD("$", "Australian Dollar"),
        JPY("¥", "Japanese Yen"),
        CNH("CN¥", "Chinese Yuan (Offshore)"),
        HKD("HK$", "Hong Kong Dollar"),
        CAD("$", "Canadian Dollar"),
        INR("₹", "Indian Rupee"),
        DKK("kr", "Danish Krone"),
        GBP("£", "British Pound Sterling"),
        RUB("₽", "Russian Ruble"),
        NZD("$", "New Zealand Dollar"),
        MXN("$", "Mexican Peso"),
        IDR("Rp", "Indonesian Rupiah"),
        TWD("NT$", "New Taiwan Dollar"),
        THB("฿", "Thai Baht"),
        VND("₫", "Vietnamese Dong"),
        ZAR("R", "South African Rand"),
        NOK("kr", "Norwegian Krone"),
        SEK("kr", "Swedish Krona"),
        CHF("Fr", "Swiss Franc"),
        KRW("₩", "South Korean Won"),
        AED("د.إ", "United Arab Emirates Dirham"),
        SAR("﷼", "Saudi Riyal"),
        PLN("zł", "Polish Zloty"),
        BRL("R$", "Brazilian Real"),
        ARS("$", "Argentine Peso"),
        CLP("$", "Chilean Peso"),
        COP("$", "Colombian Peso"),
        PEN("S/.", "Peruvian Sol"),
        PHP("₱", "Philippine Peso"),
        KWD("د.ك", "Kuwaiti Dinar"),
        EGP("E£", "Egyptian Pound"),
        IQD("ع.د", "Iraqi Dinar"),
        NGN("₦", "Nigerian Naira"),
        LBP("ل.ل", "Lebanese Pound"),
        BHD("ب.د", "Bahraini Dinar"),
        JOD("د.ا", "Jordanian Dinar"),
        QAR("﷼", "Qatari Riyal"),
        OMR("ر.ع.", "Omani Rial"),
        CNY("¥", "Chinese Yuan (Onshore)"),
        BDT("৳", "Bangladeshi Taka"),
        MOP("MOP$", "Macau Pataca"),
        LKR("Rs", "Sri Lankan Rupee"),
        NPR("रू", "Nepalese Rupee"),
        PKR("₨", "Pakistani Rupee"),
        KHR("៛", "Cambodian Riel"),
        MMK("K", "Myanmar Kyat"),
        LAK("₭", "Lao Kip"),
        KZT("₸", "Kazakhstani Tenge"),
        GEL("₾", "Georgian Lari"),
        ARM("AMD", "Armenian Dram"),
        UZS("so'm", "Uzbekistani Som"),
        TJS("ЅМ", "Tajikistani Somoni"),
        AFN("؋", "Afghan Afghani"),
        MNT("₮", "Mongolian Tugrik"),
        BND("B$", "Brunei Dollar"),
        BGN("лв", "Bulgarian Lev"),
        HRK("kn", "Croatian Kuna"),
        CZK("Kč", "Czech Koruna"),
        DOP("RD$", "Dominican Peso"),
        ISK("kr", "Icelandic Krona"),
        ILS("₪", "Israeli New Shekel"),
        HUF("Ft", "Hungarian Forint"),
        JMD("J$", "Jamaican Dollar"),
        KES("KSh", "Kenyan Shilling"),
        LTL("Lt", "Lithuanian Litas"),
        LVL("Ls", "Latvian Lats"),
        MKD("ден", "Macedonian Denar"),
        MUR("₨", "Mauritian Rupee"),
        MDL("MDL", "Moldovan Leu"),
        MAD("د.م.", "Moroccan Dirham"),
        MZN("MT", "Mozambican Metical"),
        NAD("N$", "Namibian Dollar"),
        NIO("C$", "Nicaraguan Cordoba Oro"),
        PAB("B/.", "Panamanian Balboa"),
        PYG("₲", "Paraguayan Guarani"),
        RON("lei", "Romanian Leu"),
        RSD("дин", "Serbian Dinar"),
        SVC("$", "Salvadoran Colon"),
        TMT("T", "Turkmenistani Manat"),
        UAH("₴", "Ukrainian Hryvnia"),
        UYU("U$", "Uruguayan Peso"),
        VEF("Bs", "Venezuelan Bolivar Fuerte"),
        XAF("FCFA", "Central African CFA Franc"),
        XCD("EC$", "East Caribbean Dollar"),
        XOF("CFA", "West African CFA Franc"),
        XPF("₣", "CFP Franc"),
        ZMW("ZK", "Zambian Kwacha"),
        ZWL("Z$", "Zimbabwean Dollar"),
        BTC("₿", "Bitcoin"),
        ETH("Ξ", "Ethereum"),
        LTC("Ł", "Litecoin"),
        XRP("XRP", "Ripple"),
        BCH("BCH", "Bitcoin Cash"),
        EOS("EOS", "EOS.IO"),
        XLM("XLM", "Stellar Lumens"),
        ADA("ADA", "Cardano"),
        XMR("XMR", "Monero"),
        DASH("DASH", "Dash"),
        IOTA("IOTA", "IOTA"),
        NEO("NEO", "NEO"),
        TRX("TRX", "TRON"),
        ZEC("ZEC", "Zcash"),
        BNB("BNB", "Binance Coin"),
        USDT("USDT", "Tether"),
        WAVES("WAVES", "Waves"),
        XEM("XEM", "NEM"),
        XTZ("XTZ", "Tezos"),
        LINK("LINK", "Chainlink")

}